image: Visual Studio 2022

build_script:
  - call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - msbuild BinThumbnail.sln -p:Configuration=Release;Platform=x64
  - 7z a BinThumbnail.zip install.cmd uninstall.cmd BinThumbnail.dll
  - 7z rn BinThumbnail.zip install.cmd BinThumbnail\install.cmd uninstall.cmd BinThumbnail\uninstall.cmd BinThumbnail.dll BinThumbnail\BinThumbnail.dll
  - sha1sum *.zip *.dll

artifacts:
  - path: 'BinThumbnail.zip'
